name: 3DC1 Unit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Test Platform
      working-directory: /3DC1/runner/work/CI3DC1Test/CI3DC1Test/3DC1
      run: dotnet add package Microsoft.TestPlatform --version 17.5.0

    - name: Dependency Restore
      run: dotnet restore

    - name: Project Build
      run: dotnet build

    - name: Project Test
      run: dotnet test
